controller_list:
  - name: fake_base_group_controller
    joints:
      []
  - name: fake_Arm_controller
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
  - name: fake_eef_group_controller
    joints:
      - arm_6_joint