# This file maps your CANOPEN-IDs to the joint names used in the URDF
# Syntax: node_mapping_<CANOPEN-ID>: <URDF-NAME>
node_mapping_3: arm_1_joint
node_mapping_4: arm_2_joint
node_mapping_5: arm_3_joint
node_mapping_6: arm_4_joint
node_mapping_7: arm_5_joint
node_mapping_8: arm_6_joint
#node_mapping_12: gripper
